import { mkdirSync, readFileSync, writeFileSync, cpSync, existsSync, readdirSync, unlinkSync, rmdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { validateSite, validatePosts, publishedPosts, formatDate, readingTime, escapeXml as e, citation, bibtex } from "../src/lib/content.mjs";
import { markdown } from "../src/lib/markdown.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const out = join(root, "out");
const site = validateSite(JSON.parse(readFileSync(join(root, "src", "data", "site.json"), "utf8")));
const posts = publishedPosts(validatePosts(JSON.parse(readFileSync(join(root, "src", "data", "posts.json"), "utf8"))));
const origin = site.url.replace(/\/$/, "");
const topics = [...new Set(posts.flatMap((post) => post.tags))].sort();
const parsed = new Map(posts.map((post) => [post.slug, markdown(post.body)]));
for (const post of posts) {
  if (post.pdf?.startsWith("/files/") && !existsSync(join(root, "public", post.pdf))) throw new Error(`Missing PDF for "${post.slug}": add public${post.pdf} or set pdf to null.`);
}

function clear(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) { clear(path); rmdirSync(path); } else unlinkSync(path);
  }
}
if (existsSync(out)) clear(out);
mkdirSync(out, { recursive: true });
cpSync(join(root, "public"), out, { recursive: true });
cpSync(join(root, "src", "lib", "content.mjs"), join(out, "content.mjs"));
const arrow = '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';
const link = (url, text, cls = "text-link") => `<a class="${cls}" href="${e(url)}">${text} ${arrow}</a>`;
const postUrl = (post) => `/writing/${post.slug}/`;
const topicUrl = (topic) => `/writing/?topic=${encodeURIComponent(topic)}`;
const logo = '<img class="site-logo" src="/logo.png" alt="" width="768" height="875">';
const sampleNotice = site.showSampleNotice ? '<p class="sample-notice">An editable starting point. The entries shown here are original sample writing, not the author’s published work.</p>' : "";
function row(post) {
  return `<article class="post-row" data-slug="${post.slug}"><div class="post-row-meta"><span class="kind kind-${post.type.toLowerCase()}">${post.type}</span><time datetime="${post.date}">${formatDate(post.date)}</time></div><div class="post-row-content"><h3><a href="${postUrl(post)}">${e(post.title)}${arrow}</a></h3><p>${e(post.description)}</p><div class="post-row-bottom"><span>${readingTime(post.body)} min read</span><span class="dot" aria-hidden="true">·</span><span>${e(post.tags.join(" / "))}</span></div></div></article>`;
}
function layout(title, path, description, body, article = null) {
  const canonical = `${origin}${path}`;
  const jsonLd = article ? `<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": article.type === "Paper" ? "ScholarlyArticle" : "BlogPosting", headline: article.title, description: article.description, datePublished: article.date, dateModified: article.updated ?? article.date, author: { "@type": "Person", name: site.author }, mainEntityOfPage: canonical, inLanguage: "en" }).replace(/</g, "\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${e(title)} — ${e(site.title)}</title><meta name="description" content="${e(description)}"><meta name="author" content="${e(site.author)}"><link rel="canonical" href="${e(canonical)}"><link rel="icon" type="image/png" href="/logo.png"><link rel="alternate" type="application/rss+xml" title="${e(site.title)}" href="/feed.xml"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${article ? "article" : "website"}"><meta property="og:url" content="${e(canonical)}"><meta property="og:site_name" content="${e(site.title)}"><meta property="og:image" content="${e(origin)}/logo.png"><meta property="og:image:alt" content="${e(site.title)} logo"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="${e(origin)}/logo.png">${article ? `<meta property="article:published_time" content="${article.date}"><meta property="article:modified_time" content="${article.updated ?? article.date}">` : ""}<link rel="stylesheet" href="/styles.css"><script type="module" src="/site.js"></script>${jsonLd}</head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a href="/" class="brand" aria-label="${e(site.title)} home"><span class="brand-mark">${logo}</span><span class="brand-name">${e(site.title)}<span class="brand-tagline">${e(site.tagline)}</span></span></a><nav aria-label="Main navigation">${[["/", "Home"], ["/writing/", "Writing"], ["/about/", "About"]].map(([url, name]) => `<a href="${url}"${(url === "/" ? path === "/" : path.startsWith(url)) ? ' aria-current="page"' : ""}>${name}</a>`).join("")}<a class="feed-link" href="/feed.xml" aria-label="RSS feed">RSS <span aria-hidden="true">↗</span></a></nav></div></header><main id="main" class="container">${body}</main><footer class="site-footer"><div class="container footer-inner"><div><a href="/" class="footer-title">${logo}${e(site.title)}</a><p>Considered writing. An open notebook.</p></div><div class="footer-right"><nav aria-label="Footer navigation"><a href="/writing/">Archive</a><a href="/about/">About</a><a href="/feed.xml">RSS feed</a>${site.email ? `<a href="mailto:${e(site.email)}">Contact</a>` : ""}</nav><span>© ${new Date().getUTCFullYear()} ${e(site.author)}</span></div></div></footer></body></html>`;
}
function write(path, content) {
  const target = resolve(out, path);
  if (!target.startsWith(out + "\\" ) && !target.startsWith(out + "/")) throw new Error("Output path escaped the export directory.");
  mkdirSync(resolve(target, ".."), { recursive: true });
  writeFileSync(target, content);
}
const featured = posts.find((post) => post.featured) ?? posts[0];
const latest = posts.filter((post) => post.slug !== featured?.slug).slice(0, 4);
const homeIntro = `<section class="hero" aria-labelledby="journal-heading"><div class="hero-copy"><span class="eyebrow"><span class="live-dot"></span>Essays · Research · Notes</span><h1 id="journal-heading">${e(site.headline)}</h1><p>${e(site.intro)}</p>${link("/writing/", "Explore the writing")}</div><div class="hero-margin"><span class="margin-number">01 — THE JOURNAL</span><p>Not everything needs<br>an immediate answer.</p><span class="margin-rule"></span><span>A little space to think.</span></div></section>`;
const home = `<div class="home-grid"><div>${featured ? `<section aria-labelledby="featured-heading"><div class="section-heading"><h2 id="featured-heading">Selected writing</h2><span>Worth a closer read</span></div><article class="featured"><div class="featured-top"><span class="kind">${featured.type}</span><span class="featured-label">FEATURED ↗</span></div><h3><a href="${postUrl(featured)}">${e(featured.title)}</a></h3><p>${e(featured.description)}</p><div class="featured-bottom"><span><time datetime="${featured.date}">${formatDate(featured.date)}</time><span class="dot">·</span>${readingTime(featured.body)} min read</span>${link(postUrl(featured), `Read ${featured.type.toLowerCase()}`)}</div></article></section>` : ""}<section class="latest" aria-labelledby="latest-heading"><div class="section-heading"><h2 id="latest-heading">Recent entries</h2>${link("/writing/", "View all", "")}</div>${latest.length ? latest.map(row).join("") : '<p class="muted">The journal is ready for its next entry.</p>'}</section><div class="archive-callout"><span>There’s more in the margins.</span>${link("/writing/", "Browse the full archive")}</div></div><aside class="home-sidebar"><section class="desk"><span class="eyebrow">From the desk</span><span class="desk-monogram" aria-hidden="true">${logo}</span><h2>A working collection<br>of thoughts &amp; inquiry.</h2><p>${e(site.bio)}</p>${link("/about/", "About this journal")}</section><section class="topic-section"><h2 class="eyebrow">Threads of interest</h2><div class="topic-links">${topics.map((topic) => `<a href="${topicUrl(topic)}">${e(topic)}<span>${posts.filter((post) => post.tags.includes(topic)).length}</span></a>`).join("")}</div></section><section class="rss-note"><div class="eyebrow">Stay in the loop</div><p>New writing, on your terms.<br>No algorithm. No inbox clutter.</p>${link("/feed.xml", "Subscribe via RSS")}</section></aside></div>${sampleNotice}${homeIntro}`;
write("index.html", layout(site.headline, "/", site.description, home));

const archive = `<header class="page-heading"><span class="eyebrow">The archive</span><h1>All writing<span class="title-period">.</span></h1><p>Longer arguments, shorter observations, and the questions between.</p></header><div class="archive" id="archive"><div class="search-wrap"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/></svg><label class="sr-only" for="search">Search writing</label><input id="search" type="search" placeholder="Search titles, ideas, or keywords…" disabled><span class="search-hint">The whole archive, at a glance</span></div><div class="filter-bar"><div class="type-filters" role="group" aria-label="Filter by format">${["All", "Essay", "Paper", "Note"].map((type) => `<button data-type="${type}" aria-pressed="${type === "All"}" disabled>${type === "All" ? "All writing" : type + "s"}<span>${type === "All" ? posts.length : posts.filter((post) => post.type === type).length}</span></button>`).join("")}</div><div class="select-filters"><label class="sr-only" for="topic">Filter by topic</label><select id="topic" disabled><option value="">All topics</option>${topics.map((topic) => `<option>${e(topic)}</option>`).join("")}</select><label class="sr-only" for="sort">Sort writing</label><select id="sort" disabled><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div></div><div class="results-label"><span id="result-count" role="status" aria-live="polite">${posts.length} pieces in the archive</span><button id="clear-filters" hidden>Clear filters ×</button></div><div id="post-list">${posts.map(row).join("")}</div><div class="empty-state" id="empty-state" hidden><h2>No writing found.</h2><p>Try a different keyword or give the filters a little more room.</p><button class="text-link" id="reset-archive">Reset the archive</button></div><noscript><p class="notice">Search and filters require JavaScript. All published entries are listed above.</p></noscript></div>`;
write("writing/index.html", layout("Writing", "/writing/", "The complete collection of essays, papers, and working notes.", archive));
write("posts.json", JSON.stringify(posts));

for (const post of posts) {
  const rendered = parsed.get(post.slug);
  const related = posts.filter((entry) => entry.slug !== post.slug).sort((a, b) => b.tags.filter((tag) => post.tags.includes(tag)).length - a.tags.filter((tag) => post.tags.includes(tag)).length).slice(0, 2);
  const body = `<div class="article-shell"><a class="back-link" href="/writing/">← All writing</a><article><header class="article-heading"><span class="eyebrow">${post.type}<span class="dot">/</span>${e(post.tags.join(" · "))}</span><h1>${e(post.title)}</h1><p class="article-deck">${e(post.description)}</p><div class="article-byline"><span>${e(site.author)}</span><span class="dot">·</span><time datetime="${post.date}">${formatDate(post.date, true)}</time><span class="dot">·</span><span>${readingTime(post.body)} min read</span></div>${post.updated ? `<p class="updated">Revised <time datetime="${post.updated}">${formatDate(post.updated, true)}</time></p>` : ""}</header>${post.sample ? `<p class="notice">Demonstration ${post.type.toLowerCase()} · Original sample content. Replace before publishing.</p>` : ""}${post.pdf ? `<a class="pdf-link text-link" href="${e(post.pdf)}" target="_blank" rel="noopener noreferrer">Read the paper as PDF ${arrow}</a>` : ""}${rendered.toc.length > 2 ? `<details class="article-toc"><summary>In this piece</summary><nav aria-label="Table of contents">${rendered.toc.map((heading) => `<a href="#${heading.id}">${e(heading.label)}</a>`).join("")}</nav></details>` : ""}<div class="prose">${rendered.html}</div><div class="article-end"><span aria-hidden="true">◇</span><span>End of ${post.type.toLowerCase()}</span></div><div class="article-tags">${post.tags.map((tag) => `<a href="${topicUrl(tag)}">${e(tag)}</a>`).join("")}</div><div class="citation-box"><span class="eyebrow">Cite this piece</span><p id="citation">${e(citation(post, site))}</p><div class="action-links"><button id="copy-citation" hidden>Copy citation</button><a href="${postUrl(post)}citation.bib" download="${post.slug}.bib">BibTeX ↓</a><button id="print-article" hidden>Print / save PDF</button></div><span class="action-status" id="action-status" role="status"></span></div></article>${related.length ? `<section class="related"><div class="section-heading"><h2>Continue reading</h2>${link("/writing/", "The archive", "")}</div>${related.map(row).join("")}</section>` : ""}</div>`;
  write(`writing/${post.slug}/index.html`, layout(post.title, postUrl(post), post.description, body, post));
  write(`writing/${post.slug}/citation.bib`, bibtex(post, site));
}

const about = `<header class="page-heading"><span class="eyebrow">Behind the writing</span><h1>A little context<span class="title-period">.</span></h1><p>An independent journal. A place to think in public.</p></header><div class="about-grid"><div class="about-copy"><span class="eyebrow">The writer</span><h2>${e(site.author)}</h2><p class="about-lead">${e(site.bio)}</p><h3>What you’ll find here</h3><p><strong>Essays</strong> develop an argument with room for nuance. <strong>Papers</strong> give research and structured inquiry a permanent home. <strong>Notes</strong> capture smaller observations before they disappear.</p><p>These formats share a single intention: to make the reasoning visible, not just the conclusion.</p><h3>An open notebook</h3><p>This is a personal publication, not a claim to have the last word. When a piece changes substantially, its revision date appears alongside the original publication date. Sources and further reading belong with the writing they inform.</p><h3>Read at your own pace</h3><p>Everything here is freely readable, with no account, paywall, or tracking scripts. Follow new entries through <a href="/feed.xml">the RSS feed</a>, or return to the archive when it suits you.</p>${site.email ? `<h3>Correspondence</h3><p>Thoughtful questions, corrections, and reading recommendations are welcome at <a href="mailto:${e(site.email)}">${e(site.email)}</a>.</p>` : ""}${link("/writing/", "Back to the writing")}</div><aside class="about-sidebar"><div class="about-mark" aria-hidden="true">${logo}</div><span class="eyebrow">Currently exploring</span><ul>${site.interests.map((interest) => `<li>${e(interest)}</li>`).join("")}</ul><div class="about-stats"><div><strong>${String(posts.length).padStart(2, "0")}</strong><span>published pieces</span></div><div><strong>03</strong><span>ways of thinking</span></div></div>${site.links.length ? `<div class="profile-links">${site.links.map((item) => `<a href="${e(item.url)}" target="_blank" rel="noopener noreferrer">${e(item.label)} ↗</a>`).join("")}</div>` : ""}</aside></div>${sampleNotice}`;
write("about/index.html", layout("About", "/about/", `About ${site.title}, a journal by ${site.author}.`, about));
write("404.html", layout("Page not found", "/404.html", "This page could not be found.", `<section class="not-found"><span class="eyebrow">404 / A missing page</span><h1>Not in the margins.</h1><p>This page doesn’t exist, or the address has changed.<br>The archive is a good place to pick up the thread.</p>${link("/writing/", "Find something to read")}</section>`));
write("feed.xml", `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${e(site.title)}</title><link>${e(origin)}</link><description>${e(site.description)}</description><language>en</language><atom:link href="${e(origin)}/feed.xml" rel="self" type="application/rss+xml"/>${posts.map((post) => `<item><title>${e(post.title)}</title><link>${e(origin + postUrl(post))}</link><guid isPermaLink="true">${e(origin + postUrl(post))}</guid><description>${e(post.description)}</description><pubDate>${new Date(post.date + "T00:00:00Z").toUTCString()}</pubDate>${post.tags.map((tag) => `<category>${e(tag)}</category>`).join("")}</item>`).join("")}</channel></rss>`);
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${["/", "/writing/", "/about/"].map((path) => `<url><loc>${e(origin + path)}</loc></url>`).join("")}${posts.map((post) => `<url><loc>${e(origin + postUrl(post))}</loc><lastmod>${post.updated ?? post.date}</lastmod></url>`).join("")}</urlset>`);
write("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${posts.length} articles, home, archive, about, 404, RSS and sitemap into out.`);
